CXX = gcc
CXXFLAGS = -std=c11

all: program1 program2

program1: program1.c
	$(CXX) $(CXXFLAGS) -o program1 program1.c

program2: program2.c
	$(CXX) $(CXXFLAGS) -o program2 program2.c

clean:
	rm -f program1 program2
