CXX = g++
CXXFLAGS = -std=c++17

main: linear_congruential_generator.cpp
	$(CXX) $(CXXFLAGS) -o linear_congruential_generator linear_congruential_generator.cpp

clean:
	rm -f linear_congruential_generator
